### ISSUE TITLE
AEADBadTagException Crash on Launch in Android 12 with react-native-zohosalesiq-mobilisten Version 9.3.1

### ISSUE THREAD

**Issue by MAsadIlyasNajum** [zoho/SalesIQ-Mobilisten-ReactNative#106]
We are experiencing a crash during app launch on Android 12 devices while using the react-native-zohosalesiq-mobilisten library (version 9.3.1). The crash occurs when trying to create EncryptedSharedPreferences using Android's security libraries. The error trace is related to an AEADBadTagException, specifically during decryption in the Android Keystore.

**Key error message:**

```
Fatal Exception: javax.crypto.AEADBadTagException:
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:611)
       at javax.crypto.Cipher.doFinal(Cipher.java:2132)
       at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:28)
       at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:6)
       at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:9)
       at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:8)
       at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:4)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(AndroidKeysetManager.java:20)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:54)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:51)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:5)
       at com.zoho.livechat.android.modules.common.data.local.MobilistenEncryptedSharedPreferences.getEncryptedSharedPreferences(MobilistenEncryptedSharedPreferences.kt:20)
       at com.zoho.livechat.android.modules.common.DataModule.getEncryptedSharedPreferences(DataModule.kt:26)
       at com.zoho.livechat.android.provider.MobilistenInitProvider$onCreate$1.invokeSuspend(MobilistenInitProvider.kt:10)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:1)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
```

```
Caused by android.security.KeyStoreException: Signature/MAC verification failed
       at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
       at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
       at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:127)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
       at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
       at javax.crypto.Cipher.doFinal(Cipher.java:2132)
       at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:28)
       at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:6)
       at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:9)
       at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:8)
       at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:4)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(AndroidKeysetManager.java:20)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:54)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:51)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:5)
       at com.zoho.livechat.android.modules.common.data.local.MobilistenEncryptedSharedPreferences.getEncryptedSharedPreferences(MobilistenEncryptedSharedPreferences.kt:20)
       at com.zoho.livechat.android.modules.common.DataModule.getEncryptedSharedPreferences(DataModule.kt:26)
       at com.zoho.livechat.android.provider.MobilistenInitProvider$onCreate$1.invokeSuspend(MobilistenInitProvider.kt:10)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:1)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Environment:**
Library: react-native-zohosalesiq-mobilisten v9.3.1
OS: Android 12
Device: Note
No specific logs printed before crash

**Comment by bhahirathan-mb-11956** [comment]
Hi @MAsadIlyasNajum,
 
We apologize for the inconvenience caused. The issue has already been fixed. Please update the Mobilisten SDK to the [latest version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/latest) and verify once.
 
Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.
