### ISSUE TITLE
Push notification does not work with firebase 4.3.8

### ISSUE THREAD

**Issue by hungkoala** [zoho/SalesIQ-Mobilisten-ReactNative#23]
I followed this guideline   https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-mobile-push-notification-android.html   to setup push notification but was not successful because the class FirebaseInstanceId.java  has been deleted in firebase com.google.gms:google-services:4.3.8. Could please fix it?

Here is my code example: https://github.com/hungkoala/seq3

**Comment by Angu-G** [comment]
Hello @hungkoala, You can directly use the token that you get in the onNewToken() method. We will change the same in the doc too. An example code snippet is given below.

```
@Override
public void onNewToken(String token) {
   RNZohoSalesIQ.enablePush(token, --true/false--);
}
```

**Comment by hungkoala** [comment]
i've tried and not successfully

**Comment by hungkoala** [comment]
Can see my device is on the list but did not work 

https://lh3.googleusercontent.com/pw/AM-JKLU94rssjmneGu6_rLdC37ICaU5p6Ecs5mjizxwV08NaI9iHF8XZIbSL0YALUP7rIOvohfyyFr9hj3vGWKVad8WGksK2P7IVZVUBgzY_het85OqLB_28LD0ZnO-EavSAvMA80iJRSAONSKCfeFhEiFIm=w1858-h1226-no?authuser=0

**Comment by dieptang** [comment]
Try upload it to testflight and reinstall it. It not working on debug mode

**Comment by Angu-G** [comment]
> Can see my device is on the list but did not work
> 
> https://lh3.googleusercontent.com/pw/AM-JKLU94rssjmneGu6_rLdC37ICaU5p6Ecs5mjizxwV08NaI9iHF8XZIbSL0YALUP7rIOvohfyyFr9hj3vGWKVad8WGksK2P7IVZVUBgzY_het85OqLB_28LD0ZnO-EavSAvMA80iJRSAONSKCfeFhEiFIm=w1858-h1226-no?authuser=0

Hello @hungkoala, The device is successfully registered from our end and hence it is displayed in the portal. Have you tried debugging the onMessageReceived() method?

**Comment by hungkoala** [comment]
I tried  debugging onMessageReceived but received nothing

**Comment by hungkoala** [comment]
example code is available  at https://github.com/hungkoala/seq3, please have a check

**Comment by hungkoala** [comment]
the issue caused by 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.app.Application.getSharedPreferences(java.lang.String, int)' on a null object reference
	at com.zohosalesiq.reactlibrary.RNZohoSalesIQ.handleNotification(RNZohoSalesIQ.java:920)
	at care.zoop.bewell.java.MyFirebaseMessagingService.onMessageReceived(MyFirebaseMessagingService.java:30)
	at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@22.0.0:13)
	at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@22.0.0:8)
	at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@22.0.0:3)
	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@22.0.0:3)
	at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@22.0.0:1)
	at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by Angu-G** [comment]
Hello @hungkoala, This crash is due to the **null** value of your application instance (application object is not initialized). We have given the code snippet **`MainApplication.getApplication()`**  to convey that the application instance should be passed as the first param. Initialization of the instance will be generally taken care of by the application developer (application instance will be used by the developer in other use cases too). 

Anyways we will include this in our documentation. We are working on our new UI screenshot changes in the help doc and this suggestion shall be shipped with those changes as well.
