### ISSUE TITLE
Android crash v 4.2.2 .isFormEnabled

### ISSUE THREAD

**Issue by tszajna0** [zoho/SalesIQ-Mobilisten-ReactNative#31]
# Environment
- react-native-zohosalesiq-mobilisten 4.2.2
- com.zoho.salesiq:mobilisten:4.2.1
- Android 11, Galaxy Note20 5G
issue noticed once in Crashlytics, no known reproduction steps

# Stack trace
    Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bossrevolution.money.production/com.zoho.livechat.android.ui.activities.ChatActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3835)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
       at com.zoho.livechat.android.utils.LiveChatUtil.isFormEnabled(SourceFile:3283)
       at com.zoho.livechat.android.ui.activities.ChatActivity.initChat(SourceFile:160)
       at com.zoho.livechat.android.ui.activities.ChatActivity.onCreate(SourceFile:96)
       at android.app.Activity.performCreate(Activity.java:8207)
       at android.app.Activity.performCreate(Activity.java:8191)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Angu-G** [comment]
Closing the issue since the updates will be posted on similar issue #30.

**Comment by Angu-G** [comment]
Hello @tszajna0, Thank you for your patience. This issue has been addressed in our latest [version(v4.2.4](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.4)).
