### ISSUE TITLE
App crashing leading from java.lang.NullPointerException

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#41]
Hi again, 

We got new issue sometime on Android, here is detail 

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.myapp/com.zoho.livechat.android.ui.activities.ChatActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

Device Info
```
Brand:samsung
Model:Galaxy Note9
Orientation: Portrait
RAM free: 2.77 GB
Disk free: 38.35 GB
Operating System
Version:Android 10
Orientation: Portrait
Rooted:No

```

It will be great if you found something from the log.

**Comment by Angu-G** [comment]
Hello @dieptang, The error log shared has some missing traces in-between. Can you please share us the complete log to debug the issue? Also we hope you are using our latest [version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.8).
