### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by davepaiva** [zoho/SalesIQ-Mobilisten-ReactNative#42]
Hello Zoho team,
We are getting the below error **stack trace via Firebase Crashlytics**:
```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
	at com.zoho.salesiqembed.ZohoSalesIQ.syncThemeWithOS(ZohoSalesIQ.java:372)
	at com.reactlibrary.RNZohoSalesIQ$53.run(RNZohoSalesIQ.java:932)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8183)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

       at .<unknown>(com.zoho.salesiqembed.ZohoSalesIQ.syncThemeWithOSZohoSalesIQ.java:372:0)
       at .<unknown>(com.reactlibrary.RNZohoSalesIQ$53.runRNZohoSalesIQ.java:932:0)
       at .<unknown>(android.os.Handler.handleCallbackHandler.java:938:0)
       at .<unknown>(android.os.Handler.dispatchMessageHandler.java:99:0)
       at .<unknown>(android.os.Looper.loopLooper.java:257:0)
       at .<unknown>(android.app.ActivityThread.mainActivityThread.java:8183:0)
       at .<unknown>(com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runRuntimeInit.java:626:0)
       at .<unknown>(com.android.internal.os.ZygoteInit.mainZygoteInit.java:1015:0)
       at .<unknown>(395.js:1:1453)
       at .c.value(28.js:1:3977)
       at .<unknown>(28.js:1:1147)
       at .c.value(28.js:1:2938)
       at .c.value(28.js:1:1126)
 ```
**environment info** 
```
       OS - Android 11
       Device  - V2052
       React Native version - 0.61.5
       react-native-zohosalesiq-mobilisten version - 2.0.0
 ```
Looking forward to suggestions and next steps to pinpoint and fix the issue
Thank you

**Comment by Angu-G** [comment]
Hello @davepaiva, Thanks for your patience. Can you help us with the order of the syncThemeWithOS API call?  Please ensure it is triggered only after successful init completion.

**Comment by DavidBhahirathan** [comment]
Hi @davepaiva  ,

As there is no recent activity, we're closing this issue from our side. You can reopen again anytime. Meanwhile, please check out our latest version [version(v4.2.10](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.10)). 

For further queries, please feel free to write us at [support@zohosalesiq.com]. We will be happy to assist you. 

Best regards,
Bhahirathan
