### ISSUE TITLE
Crashlytics issues (ZohoLiveChat.java line 301, LiveChatUtil.java line 181)

### ISSUE THREAD

**Issue by wiedzmin26** [zoho/SalesIQ-Mobilisten-ReactNative#6]
"react-native-zohosalesiq-mobilisten": "^1.3.5"

**ZohoLiveChat.java line 301**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
       at com.zoho.livechat.android.ZohoLiveChat$Chat.setVisibility(ZohoLiveChat.java:301)
       at com.reactlibrary.RNZohoSalesIQ$40.run(RNZohoSalesIQ.java:742)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**LiveChatUtil.java line 181**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.content.SharedPreferences.getString(java.lang.String, java.lang.String)' on a null object reference
       at com.zoho.livechat.android.utils.LiveChatUtil.getCVUID(LiveChatUtil.java:181)
       at com.zoho.livechat.android.utils.LiveChatUtil.setCVUID(LiveChatUtil.java:186)
       at com.zoho.livechat.android.ZohoLiveChat.registerVisitor(ZohoLiveChat.java:1081)
       at com.reactlibrary.RNZohoSalesIQ$33.run(RNZohoSalesIQ.java:655)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by Angu-G** [comment]
Hello @wiedzmin26, Any API that is triggered before init() will cause this crash. Please use ZohoSalesIQ.registerVisitor() API (or any other APIs used) after ZohoSalesIQ.init() API is being called.

**Comment by Angu-G** [comment]
@wiedzmin26, We are closing this issue now. You can get back to us if you face any crash.

**Comment by dhruvjain1800** [comment]
HI
I am facing this error now. I have called ZohoSalesIQ.init() in App.js hence it should be called before any other apis.

**Comment by Angu-G** [comment]
Hi @dhruvjain1800, SDK should always be initialized at the Application level. In React-Native case, we recommend initializing the SDK in `useEffect` or `componentDidMount` method.

**Comment by dhruvjain1800** [comment]
This is my component did mount function in app.js

`componentDidMount() {

      ZohoSalesIQ.init(zohoAppKey(), zohoAccessKey());
      ZohoSalesIQ.setLauncherVisibility(false);
      ZohoSalesIQ.disableInAppNotification();
      ZohoSalesIQ.disablePreChatForms();
    
    }

  }`

I have initialized SDK here. Is there something I am doing wrong?

**Comment by Angu-G** [comment]
@dhruvjain1800, Can you please share with us the exact crash log or screenshot of the issue you facing.

**Comment by dhruvjain1800** [comment]
@Angu-G Here it is-

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
       at com.zoho.livechat.android.ZohoLiveChat$Notification.disableInApp(ZohoLiveChat.java:843)
       at com.reactlibrary.RNZohoSalesIQ$39.run(RNZohoSalesIQ.java:722)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6977)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)`

**Comment by Angu-G** [comment]
Thanks for sharing the logs @dhruvjain1800. We would recommend you to remove the above codes and try using the initWithCallback() method and let us know the result.

```
ZohoSalesIQ.initWithCallback("your appKey","your accessKey", (success) => {
      if(success){
          ZohoSalesIQ.setLauncherVisibility(false);
          ZohoSalesIQ.disableInAppNotification();
          ZohoSalesIQ.disablePreChatForms();
      }
      else{
          // your code
      }
});
```

**Comment by dhruvjain1800** [comment]
@Angu-G still facing the same issue. Replaced the code with initwithcallback.

**Comment by Angu-G** [comment]
@dhruvjain1800 Sorry for missing out the reply. As we already mentioned initializing SDK with `initWithCallback()` and inside the `useEffect` or `componentDidMount` method should avoid this kind of issue.
If you still face this one, can you please drop a mail to **support@zohosalesiq.com** to help with a session?
