### ISSUE TITLE
java.lang.NullPointerException (com.zoho.livechat.android.ui.fragments.ChatFragment.onBackPressed)

### ISSUE THREAD

**Issue by Ramanpreet6262** [zoho/SalesIQ-Mobilisten-ReactNative#61]
Hi, we are getting reports of this crash on firebase crashlytics

**Stack trace:**

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler com.zoho.livechat.android.operation.SalesIQApplicationManager.getHandler()' on a null object reference
       at com.zoho.livechat.android.ui.fragments.ChatFragment.onBackPressed(ChatFragment.java:3111)
       at com.zoho.livechat.android.ui.activities.ChatActivity.onBackPressed(ChatActivity.java:108)
       at android.app.Activity.onKeyUp(Activity.java:3185)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2743)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3503)
       at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:409)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6019)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5877)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5339)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5358)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5525)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5366)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5582)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5339)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5358)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5366)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5339)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5358)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5558)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5723)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2860)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2355)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2346)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2837)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:190)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)`
       
       
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/28749866/205851030-35b60dec-906a-4a77-b95d-37706c6bf7e6.png">
<img width="882" alt="image" src="https://user-images.githubusercontent.com/28749866/205851130-0b97a2ee-9f3c-41e3-9c3f-bdd2ec8e42bb.png">

- Happening on Android
- React Native version `"0.66.5"`
- SDK Version `"react-native-zohosalesiq-mobilisten": "4.2.10"`

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

The above crash has been fixed in version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.0.0).

Regards,
Bhahirathan M,
Zoho SalesIQ.
