### ISSUE TITLE
NoClassDefFoundError DrawableWrapper

### ISSUE THREAD

**Issue by vikasporwal625** [zoho/SalesIQ-Mobilisten-ReactNative#81]
## Environment
System:
  OS: macOS 14.2.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 281.69 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: Not Found
  npm:
    version: 9.9.2
    path: ~/Projects/thrive_consumer_app/node_modules/.bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Platforms
Android

## Versions
- SalesIQ-Mobilisten-ReactNative: 8.0.2
- react-native: 0.73.1
- react: 18.2.0

## Description
FATAL EXCEPTION: main
Process: com.thrivenow, PID: 25941
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/graphics/drawable/DrawableWrapper;
	at androidx.appcompat.widget.MenuPopupWindow.createDropDownListView(MenuPopupWindow.java:80)
	at androidx.appcompat.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1178)
	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java:663)
	at androidx.appcompat.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:181)
	at androidx.appcompat.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:208)
	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:296)
	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:182)
	at androidx.appcompat.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:792)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.graphics.drawable.DrawableWrapper" on path: DexPathList[[zip file "/data/app/~~C762GN9HRBSPIw_fcgM1TQ==/com.thrivenow-e7wjdhaVZrxcbNcyX07gBw==/base.apk"],nativeLibraryDirectories=[/data/app/~~C762GN9HRBSPIw_fcgM1TQ==/com.thrivenow-e7wjdhaVZrxcbNcyX07gBw==/lib/arm64, /data/app/~~C762GN9HRBSPIw_fcgM1TQ==/com.thrivenow-e7wjdhaVZrxcbNcyX07gBw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 16 more

**Comment by bhahirathan-mb-11956** [comment]
Hi @vikasporwal625 ,

Thank you for reaching out to us. This error may occur when the appcompat dependency is used with a strict version.

```
implementation ('androidx.appcompat:appcompat:${your_version}') {
        version {
            strictly '${your_version}'
        }
    }
```

The above snippet will make the appcompat library strictly use the 1.3.1 version, but our SDK version points to version 1.6.1 . Since our SDK is trying to open a class or function that is present only in 1.6.1 but not in the old version of 1.3.1.

So, removing your dependency or the strictly function will work. If this persists, please write us at (support@zohosalesiq.com). We will be happy to help. 

Best regards,
Bhahirathan M
Zoho SalesIQ.
