### ISSUE TITLE
Fatal Exception: at SalesIQApplicationManager.java

### ISSUE THREAD

**Issue by BaluNaik** [zoho/SalesIQ-Mobilisten-ReactNative#84]
App is crashing on android version of react native.

**react-native-zohosalesiq-mobilisten ---> 8.0.4
react-native ---> 0.72.5**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at com.zoho.livechat.android.operation.SalesIQApplicationManager.onActivityStarted(SalesIQApplicationManager.java:139)
       at com.zoho.livechat.android.api.GetAndroidChannel.lambda$run$0(GetAndroidChannel.java:265)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8248)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by bhahirathan-mb-11956** [comment]
Hi @BaluNaik ,

Apologies for the inconvenience caused. We have fixed this crash in our current development, which will be released shortly. We will update you here once it is live.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @BaluNaik ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [8.0.6](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v8.0.6), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M,
Zoho SalesIQ.
