### ISSUE TITLE
ArrayIndexOutOfBoundsException at SalesIQApplicationManager.java

### ISSUE THREAD

**Issue by BaluNaik** [zoho/SalesIQ-Mobilisten-ReactNative#85]
App is crashing on android version of react native.

react-native-zohosalesiq-mobilisten ---> 8.0.4
react-native ---> 0.72.5

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.zoho.livechat.android.operation.SalesIQApplicationManager.onActivityDestroyed(SalesIQApplicationManager.java:239)
       at com.zoho.livechat.android.modules.common.ui.lifecycle.SalesIQActivitiesManager.onActivityDestroyed(SalesIQActivitiesManager.kt:84)
       at android.app.Application.dispatchActivityDestroyed(Application.java:276)
       at android.app.Activity.onDestroy(Activity.java:2003)
       at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:258)
       at android.app.Activity.performDestroy(Activity.java:7403)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4481)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by bhahirathan-mb-11956** [comment]
Hi @BaluNaik ,

Apologies for the inconvenience caused. We have fixed this crash in our current development, which will be released shortly. We will update you here once it is live.

Until then, to avoid this crash, kindly check if you have implemented [step 6](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html#:~:text=Step%206%3A%20Setup%20the%20Lifecycle%20Callback%C2%A0) properly in your project and verify once.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @BaluNaik ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [8.0.6](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v8.0.6), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M,
Zoho SalesIQ.
