### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by shubhangsati** [zoho/SalesIQ-Mobilisten-ReactNative#87]
Hi
We are getting reports of this crash on Android. Please suggest a fix for this. 

Stack trace:
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.zoho.livechat.android.modules.conversations.domain.entities.LeaveMessageResponse.isConversationStarted()' on a null object reference
    at com.zoho.livechat.android.modules.messages.ui.ChatViewModel$leaveAsMissedConversation$4.invokeSuspend(ChatViewModel.kt:496)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`

Versions:    
"react-native": "0.71.7"
"react-native-zohosalesiq-mobilisten": "^6.1.0"

**Comment by bhahirathan-mb-11956** [comment]
Hi @shubhangsati ,

We apologize for the inconvenience caused. The issue has already been fixed. Please update the Mobilisten SDK to the [latest version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/latest) and verify once.

Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists. 

Regards,
Bhahirathan M,
Zoho SalesIQ.
