### ISSUE TITLE
Preconditions.outOfBounds Exception

### ISSUE THREAD

**Issue by BaluNaik** [zoho/SalesIQ-Mobilisten-ReactNative#93]
The app is crashing on the Android version of react native.

react-native-zohosalesiq-mobilisten ---> 9.3.1
react-native ---> 0.73.6

`Unable to start activity ComponentInfo{com.namshi.android.dev/com.zoho.livechat.android.ui.activities.SalesIQActivity}: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0`

       Caused by java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
       at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
       at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
       at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
       at java.util.Objects.checkIndex(Objects.java:359)
       at java.util.ArrayList.get(ArrayList.java:434)
       at com.zoho.livechat.android.ui.adapters.SalesIQPagerAdapter.getItem(SalesIQPagerAdapter.kt:92)
       at com.zoho.livechat.android.ui.activities.SalesIQActivity.setTitleInActionBar(SalesIQActivity.java:353)
       at com.zoho.livechat.android.ui.activities.SalesIQActivity.onCreate(SalesIQActivity.java:269)
       at android.app.Activity.performCreate(Activity.java:8129)
       at android.app.Activity.performCreate(Activity.java:8109)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by bhahirathan-mb-11956** [comment]
Hi @BaluNaik,
 
We apologize for the inconvenience caused. We'll look into this crash and update you.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by BaluNaik** [comment]
@bhahirathan-mb-11956 

 Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler com.zoho.livechat.android.operation.SalesIQApplicationManager.getHandler()' on a null object reference
       at com.zoho.livechat.android.api.GetFormConfiguration.run(GetFormConfiguration.java:94)
