### ISSUE TITLE
When i am running the application after implementation of zohosalesiq i have facing those issues

### ISSUE THREAD

**Issue by Anilfeker21** [zoho/SalesIQ-Mobilisten-ReactNative#99]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/android/app/build.gradle' line: 269

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installEnvQaDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/android/app/build.gradle' line: 269

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (/Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/node_modules/execa/index.js:174:9)
    at /Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by bhahirathan-mb-11956** [comment]
Hi @Anilfeker21
 
It looks like you are using `compile` instead of `implementation` in your app's build.gradle file at line number: 269 , So kindly build the project after this change and let us know if you are still facing any issues.
 
> FAILURE: Build failed with an exception.
 
> Where:
> Build file '/Users/bharathkumar/Documents/zohoo/DriverMobileApp/src_tinting/android/app/build.gradle' line: 269
 
> compile 'your-app-dependency'
to
> implementation 'your-app-dependency'
 
Gradle documentation [link](https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_6.0) for reference.
 
Regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @Anilfeker21,

As there is no recent activity from your side, we are closing this issue. You can reopen this again anytime. Meanwhile, please check out our [latest version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/latest).

Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Best regards,
Bhahirathan M
Zoho SalesIQ.
